// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ankit Chahal",
            "url": "none",
            "email": "https://github.com/ankitchahal20/url-shortner"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/urlshortner": {
            "get": {
                "description": "Get orginal URL for a short URL",
                "consumes": [
                    "application/json"
                ],
                "summary": "Get orginal URL for a short URL",
                "parameters": [
                    {
                        "description": "Request Fields",
                        "name": "RequestFields",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.URLInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    }
                }
            }
        },
        "/v1/urlshortner/create": {
            "post": {
                "description": "Fetches a short URL for a given long URL",
                "consumes": [
                    "application/json"
                ],
                "summary": "Fetches a short URL for a given long URL",
                "parameters": [
                    {
                        "description": "Request Fields",
                        "name": "RequestFields",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.URLInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/error.URLShortnerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "error.URLShortnerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "trace": {
                    "type": "string"
                }
            }
        },
        "models.URLInfo": {
            "type": "object",
            "properties": {
                "originalurl": {
                    "type": "string"
                },
                "shorturl": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/urlshortner",
	Schemes:          []string{"http"},
	Title:            "URL Shortner",
	Description:      "This is a URL Shortner service. For a given long URL, it gives you a short URL. You can visit the GitHub repository at https://github.com/ankitchahal20/url-shortner",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
